name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create artifact
        run: |
          zip -r deployment.zip . -x "*.git*"

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "deployment.zip"
          target: "/tmp"
    
      - name: Execute deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "解压文件中..."
            unzip -o /tmp/deployment.zip -d /opt/1panel/docker/compose/anti-advertising-telegram-bot-deploy

            echo "同步文件到目标目录，排除 data 目录..."
            rsync -av --delete --exclude 'data' /opt/1panel/docker/compose/anti-advertising-telegram-bot-deploy/ /opt/1panel/docker/compose/anti-advertising-telegram-bot/

            echo "清理临时文件..."
            rm -rf /opt/1panel/docker/compose/anti-advertising-telegram-bot-deploy
            rm /tmp/deployment.zip

            echo "重启 Docker 容器..."
            docker compose -f /opt/1panel/docker/compose/anti-advertising-telegram-bot/docker-compose.yml down
            docker compose -f /opt/1panel/docker/compose/anti-advertising-telegram-bot/docker-compose.yml up -d

