name: Deploy

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create artifact
        run: |
          zip -r deployment.zip . -x "*.git*"

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "deployment.zip"
          target: "/tmp"
    
      - name: Execute deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
              # 解压文件
              unzip -o /tmp/deployment.zip -d /opt/1panel/docker/compose/anti-advertising-telegram-bot-deploy
    
              # 移动文件，采用覆盖模式
              mv -f /opt/1panel/docker/compose/anti-advertising-telegram-bot-deploy/* /opt/1panel/docker/compose/anti-advertising-telegram-bot/
    
              # 删除 index2 文件夹
              rm -rf /opt/1panel/docker/compose/anti-advertising-telegram-bot-deploy
    
              # 清理临时文件
              rm /tmp/deployment.zip

              # 停止原镜像
              docker compose down

              # 构建镜像并运行
              docker compose -f /opt/1panel/docker/compose/anti-advertising-telegram-bot/docker-compose.yml up -d