name: Docker

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  IMAGE_NAME: anti-advertising-telegram-bot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: woodchen
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: woodchen/${{ env.IMAGE_NAME }}:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "deployment.zip"
          target: "/tmp"
    
      - name: Execute deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
              # 解压文件
              unzip -o /tmp/deployment.zip -d /opt/1panel/docker/compose/anti-advertising-telegram-bot-deploy
    
              # 移动文件，采用覆盖模式
              mv -f /opt/1panel/docker/compose/anti-advertising-telegram-bot-deploy/* /opt/1panel/docker/compose/anti-advertising-telegram-bot/
    
              # 删除 index2 文件夹
              rm -rf /opt/1panel/docker/compose/anti-advertising-telegram-bot-deploy
    
              # 清理临时文件
              rm /tmp/deployment.zip

              # 构建镜像并运行
              docker-compose -f /opt/1panel/docker/compose/anti-advertising-telegram-bot/docker-compose.yml up -d